### ISSUE TITLE
Add support to System Manager and Key Management Service

### ISSUE THREAD

**Issue by StErMi** [Open-SL/serverless-permission-generator#15]
Hi all,

serverless framework supports those two systems in order to include secrets into your serverless application via env variables. It would be cool to have support for them into the configuration!

**Comment by nadunindunil** [comment]
Hi @StErMi ,

I have these system manager policies. Can you share any Key manager related policies if you have any,

Parameter store related policies:
```
- Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:GetParameterHistory
                  - ssm:GetParametersByPath
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:DeleteParameters
                  - ssm:DescribeParameters
                Resource: "*"
```

**Comment by rvanlaarhoven** [comment]
The following should be enough to read and decrypt SSM parameters

```
- Effect: Allow
  Action:
    - ssm:DescribeParameters
    - ssm:GetParameter
    - ssm:GetParameters
    - ssm:GetParametersByPath
  Resource: '*'
- Effect: Allow
  Action:
    - kms:Decrypt
  Resource: '*'
```
